name: AWS Build

on: 
  workflow_call:
    inputs: 
      trigger_type:
        required: true
        type: string
      runner:
        required: false
        type: string
        default: 'ubuntu-latest'
      env_check:
        required: false
        type: string
        description: "Environment status checker"
      new_stage:
        required: false
        type: string
        description: "New stage for deploy check flag"
        default: "false"
      stage:
        required: true
        type: string
        description: "Stage name for infrastructure deployment"
      release_version:
        required: true
        type: string
        description: "Semantic versioning for production environment"
      notifications:
        required: false
        type: boolean
        default: true
        description: "Enable notifications to cloud or team owner flag"
      only_plan:
          required: false
          type: boolean
          default: false
          description: "Enable notifications to cloud or team owner flag"
    secrets: 
      CICD_AWS_ACCESS_KEY_ID:
        required: true
      CICD_AWS_SECRET_ACCESS_KEY:
        required: true
      CICD_AWS_REGION:
        required: true
      GOOGLE_WEBHOOK:
        required: true
      TF_API_TOKEN:
        required: true
      ACTIONS_TOKEN:
        required: true

jobs:
  terraform:
      name: "Terraform"
      runs-on: ${{ inputs.runner }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              .infra
            fetch-depth: 0

        - name: Input checks
          shell: bash
          working-directory: .infra/terraform
          run: |
            echo "github_event: "${{github.event_name }}
            echo "github_branch: "${{github.ref}}
            echo "runner: "${{ inputs.runner }}
            echo "new_stage: "${{ inputs.new_stage }}
            echo "stage: "${{inputs.stage}}
            echo "release_version: "${{inputs.release_version}}

        - name: Configure AWS Credentials - Terraform
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.TF_AWS_REGION }}

        # - name: Set Global Terraform Variables
        #   shell: bash
        #   run: |
        #     export TF_VAR_account_id_list='${{secrets.TF_VAR_ACCOUNT_ID_LIST}}'
        #     export TF_VAR_terraform_role_name="${{secrets.TF_VAR_TERRAFORM_ROLE_NAME}}"
        #     export TF_VAR_github_token="${{secrets.TF_VAR_GITHUB_TOKEN}}"

        - name: Generate terraform.auto.tfvars for environment
          id: tfvars_generator
          shell: bash
          working-directory: .infra
          run: |
            if [ ${{inputs.stage}} == 'production' ] || [ ${{inputs.stage}} == 'beta' ]; then \
              jq --argjson new_env '{"new_env": ${{ inputs.new_stage }}}' --arg commit_id "$(git rev-parse --short HEAD)" --arg version ${{inputs.release_version}} '.commit_id += $commit_id | (.env_settings[]) += {new_env: false} | .env_settings |= map(if .stage == "${{inputs.stage}}" then . += $new_env + {release_version: $version} else . end)' infra-config.json > ./terraform/terraform.auto.tfvars.json              
            else \
              jq --argjson new_env '{"new_env": ${{ inputs.new_stage }}}' --arg commit_id "$(git rev-parse --short HEAD)" '.commit_id += $commit_id | (.env_settings[]) += {new_env: false} | .env_settings |= map(if .stage == "staging${{inputs.stage}}" then . += $new_env else . end)' infra-config.json > ./terraform/terraform.auto.tfvars.json
            fi
            terraform fmt
            cat ./terraform/terraform.auto.tfvars.json

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3.0.0
          with:
            #terraform_version: 1.5.3
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
        # - uses: terraform-cache/terraform-cache@v1

        - name: Terraform Format
          id: fmt
          run: terraform fmt -check -recursive -diff
          working-directory: .infra/terraform

        - name: Terraform Init
          id: init
          run: terraform init                    
          working-directory: .infra/terraform
        
        # - name: Terraform Validate
        #   id: validate
        #   run: terraform validate -no-color
        #   working-directory: .infra/terraform

        - name: Terraform Apply Staging
          if: ${{ !contains(fromJSON('["production", "beta"]'), inputs.stage) }}
          id: infra-apply-staging
          run: |
            terraform apply -auto-approve -input=false \
            -target='module.shared' \
            -target='module.staging["staging${{ inputs.stage }}"]'
          working-directory: .infra/terraform

        - name: Google Chat Notification - Staging
          if: ${{ !contains(fromJSON('["production", "beta"]'), inputs.stage) }}
          uses: nakamuraos/google-chat-notifications@v2.1.0
          with:
            title: Infrastructure Apply
            subtitle: Staging - ${{ inputs.stage }}
            webhookUrl: ${{ secrets.GOOGLE_WEBHOOK }}
            status: ${{ steps.infra-apply-staging.outcome }}

        - name: Terraform Plan Beta
          if: contains( inputs.stage, 'beta' ) && inputs.only_plan
          id: plan-beta
          run: |
            terraform plan -no-color -input=false \
            -target='module.shared' \
            -target='module.prod["beta"]'
          continue-on-error: true
          working-directory: .infra/terraform
        
        - name: Terraform Plan Prod
          if: contains( inputs.stage, 'production' ) && inputs.only_plan
          id: plan-prod
          run: |
            terraform plan -no-color -input=false \
            -target='module.shared' \
            -target='module.prod["production"]'
          continue-on-error: true
          working-directory: .infra/terraform

        - name: Terraform Plan Beta Status
          if: steps.plan-beta.outcome == 'failure'
          run: exit 1
        
        - name: Terraform Plan Prod Status
          if: steps.plan-prod.outcome == 'failure'
          run: exit 1

        - name: Terraform Apply Beta
          if: inputs.stage == 'beta' && !inputs.only_plan
          id: infra-apply-beta
          run: |
            terraform apply -auto-approve -input=false \
            -target='module.shared' \
            -target='module.prod["beta"]'        
          working-directory: .infra/terraform

        - name: Terraform Apply Prod
          if: inputs.stage == 'production' && !inputs.only_plan
          id: infra-apply-production
          run: |
            terraform apply -auto-approve -input=false \
            -target='module.shared' \
            -target='module.prod["production"]' 
          working-directory: .infra/terraform

        - name: Google Chat Notification - Beta
          if: inputs.stage == 'beta'
          uses: nakamuraos/google-chat-notifications@v2.1.0
          with:
            title: Infrastructure Apply
            subtitle: ${{ inputs.stage }}
            webhookUrl: ${{ secrets.GOOGLE_WEBHOOK }}
            status: ${{ steps.infra-apply-beta.outcome }}

        - name: Google Chat Notification - Production
          if: inputs.stage == 'production'
          uses: nakamuraos/google-chat-notifications@v2.1.0
          with:
            title: Infrastructure Apply
            subtitle: ${{ inputs.stage }}
            webhookUrl: ${{ secrets.GOOGLE_WEBHOOK }}
            status: ${{ steps.infra-apply-production.outcome }}
