name: AWS Build

on: 
  workflow_call:
    inputs: 
      runner:
        required: false
        type: string
        default: 'ubuntu-latest'
      notifications:
        required: false
        type: boolean
        default: true
        description: "Enable notifications to cloud or team owner flag"
    outputs:
      new_stage:
        description: "New stage deployment check flag"
        value: ${{ jobs.aws-build.outputs.new_stage }}
      env_check:
        description: "Environment status checker"
        value: ${{ jobs.aws-build.outputs.env_check }}
      stage_check:
        description: "Stage status checker"
        value: ${{ jobs.aws-build.outputs.stage_check }}
      stage:
        description: "Stage name for infrastructure deployment"
        value: ${{ jobs.aws-build.outputs.stage }}
      release_version:
        description: "Semantic versioning for production environment"
        value: ${{ jobs.aws-build.outputs.release_version }}
    secrets: 
      CODEBUILD_PROJECT_PROD:
        required: true
      CODEBUILD_PROJECT_STAGING:
        required: true
      CICD_AWS_ACCESS_KEY_ID:
        required: true
      CICD_AWS_SECRET_ACCESS_KEY:
        required: true
      CICD_AWS_REGION:
        required: true
      GOOGLE_WEBHOOK:
        required: true

jobs:
  aws-build:
    runs-on: ${{ inputs.runner }}
    name: AWS CodeBuild Trigger and Helm Push
    outputs:
      new_stage: ${{ steps.check-project.outputs.new_stage }}
      stage_check: ${{ steps.check-project.outputs.project_exist }}
      stage: ${{ steps.set_project_name.outputs.stage }}
      env_check: ${{ steps.check-project.outcome }}
      release_version: ${{ steps.set_project_name.outputs.release_version}}
    steps:
      - name: Checkout
        if: github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set release version
        if: github.event_name == 'release'
        id: prod-release-version-release
        run: |
          echo "Event name: "${{github.event_name}}
          echo "Target Branch: "${{github.base_ref}}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV &&
          echo "Release version: "${GITHUB_REF#refs/*/} ; \

      - name: Set PR release version
        if: github.event_name == 'pull_request'
        id: prod-release-version-pull-request
        run: |
          echo "Event name: "${{github.event_name}}
          echo "Target Branch: "${{github.base_ref}}
          if [[ ${{github.base_ref}} == "master" ]]; \
          then \
            echo "RELEASE_VERSION=prodproduction" >> $GITHUB_ENV &&
            echo "Release version: prodproduction"; \
          elif [[ ${{github.base_ref}} == "beta" ]]; \
          then \
            echo "RELEASE_VERSION=prodbeta" >> $GITHUB_ENV &&
            echo "Release version: prodbeta" ; \
          fi

      - name: Extract branch name
        id: extract_branch
        if: github.event_name == 'release' || github.event_name == 'pull_request'
        shell: bash
        run: |
          if [[ ${{github.event_name}} == 'pull_request' ]]; \
          then \
            BRANCH_NAME=${{ github.base_ref}}
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV ; \
          else \
            BRANCH_NAME=$(git branch -r --contains ${{github.sha}} | cut -d/ -f 2) &&
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV ; \
          fi

      - name: Get AWS Codebuild project
        if: github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'pull_request'
        id: set_project_name
        shell: bash
        run: |
          if [[ $BRANCH_NAME == "master" ]]; \
          then \
          echo "PROJECT=$(echo ${{secrets.CODEBUILD_PROJECT_PROD}}-production)" >> $GITHUB_ENV; \
          elif [[ $BRANCH_NAME == "beta" ]];\
          then \
          echo "PROJECT=$(echo ${{secrets.CODEBUILD_PROJECT_PROD}}-beta)" >> $GITHUB_ENV; \
          else \
          echo "PROJECT=$(echo ${{secrets.CODEBUILD_PROJECT_STAGING}}-$BRANCH_NAME)" >> $GITHUB_ENV; \
          fi
          echo "::set-output name=stage::$BRANCH_NAME"
          echo "::set-output name=release_version::$RELEASE_VERSION"
      
      - name: Configure AWS Credentials
        if: github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'pull_request'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CICD_AWS_REGION }}

      - name: Check if project exists
        if: github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'pull_request'
        id: check-project
        shell: bash
        continue-on-error: true
        run: |
          PROJECT_EXIST=$(aws codebuild list-projects --region ${{ secrets.CICD_AWS_REGION }} --query 'projects[?contains(@,`${{ env.PROJECT }}`) == `true`]' | jq -e 'length > 0')
          echo "Project exist: "$PROJECT_EXIST
          echo "::set-output name=project_exist::$PROJECT_EXIST"
          if [[ $PROJECT_EXIST == "true" ]]; \
          then \
            echo "::set-output name=new_stage::'false'"; \
          elif [[ $PROJECT_EXIST == "false" ]]; \
          then \
            echo "::set-output name=new_stage::'true'"; \
          fi
        
      - name: Run AWS CodeBuild
        id: codebuild
        if: steps.check-project.outputs.project_exist=='true' && ( github.event_name == 'release' || github.event_name == 'push' )
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ env.PROJECT }}
          env-vars-for-codebuild: |
            RELEASE_VERSION
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: Google Chat Notification
        if: steps.check-project.outputs.project_exist=='true' && ( github.event_name == 'release' || github.event_name == 'push' ) 
        uses: nakamuraos/google-chat-notifications@v2.0.1
        with:
          title: Image Build
          subtitle: ${{ env.RELEASE_VERSION }}
          webhookUrl: ${{ secrets.GOOGLE_WEBHOOK }}
          status: ${{ steps.codebuild.outcome }}

      - name: Pull request outputs set
        shell: bash
        working-directory: .infra/terraform
        run: |
          echo "new_stage: " ${{ steps.check-project.outputs.new_stage }}

      - name: Output checks
        shell: bash
        working-directory: .infra/terraform
        run: |
          echo "new_stage: " ${{ steps.check-project.outputs.new_stage }}
          echo "stage_check: " ${{ steps.check-project.outputs.project_exist }}
          echo "stage: " ${{ steps.set_project_name.outputs.stage }}
          echo "env_check: " ${{ steps.check-project.outcome }}
          echo "release_version: " ${{ steps.set_project_name.outputs.release_version}}
