name: AWS Build

on: 
  workflow_call:
    inputs: 
      trigger_type:
        required: true
        type: string
      stage:
        required: false
        type: string
      runner:
        required: false
        type: string
        default: 'ubuntu-latest'
      notifications:
        required: false
        type: boolean
        default: true
        description: "Enable notifications to cloud or team owner flag"
      infra_templates_version:
        required: false
        type: string
        default: master
        description: "Infra template version for get all configuration files"
      force_build:
        required: false
        type: boolean
        default: false
        description: "Force a codebuild pipeline run"
      branching_mode:
        required: false
        type: string
        default: gitflow
        description: "Repository branching strategy"

    outputs:
      new_stage:
        description: "New stage deployment check flag"
        value: ${{ jobs.codebuild-check.outputs.new_stage }}
      env_check:
        description: "Environment status checker"
        value: ${{ jobs.aws-build.outputs.env_check }}
      stage_check:
        description: "Stage status checker"
        value: ${{ jobs.codebuild-check.outputs.project_exist }}
      stage:
        description: "Stage name for infrastructure deployment"
        value: ${{ jobs.sets-variables.outputs.STAGE }}
      release_version:
        description: "Semantic versioning for production environment"
        value: ${{ jobs.aws-build.outputs.release_version }}
    secrets: 
      CICD_AWS_ACCESS_KEY_ID:
        required: true
      CICD_AWS_SECRET_ACCESS_KEY:
        required: true
      CICD_AWS_REGION:
        required: true
      GOOGLE_WEBHOOK:
        required: true

jobs:

  sets-variables:
    runs-on: ${{ inputs.runner }}
    name: Sets Variables
    outputs:
      COMMIT_HASH: ${{ steps.get-commit-ids.outputs.COMMIT_HASH }}
      SHORT_COMMIT_HASH: ${{ steps.get-commit-ids.outputs.SHORT_COMMIT_HASH }}
      RELEASE_TAG: ${{ steps.version-tag.outputs.RELEASE_TAG }}
      ENVIRONMENT: ${{ steps.stage.outputs.ENVIRONMENT }}
      STAGE: ${{ steps.stage.outputs.STAGE }}
      STAGE_SHORT: ${{ steps.stage.outputs.STAGE_SHORT }}
      SERVICE_NAME: ${{ steps.set-project-name.outputs.SERVICE_NAME }}
      PROJECT: ${{ steps.set-project-name.outputs.PROJECT }}
    steps:   

      - name: Check Inputs
        id: check-inputs
        run: |
          echo "Checking job inputs...."
          echo "trigger_type: ${{inputs.trigger_type}}"
          echo "stage: ${{inputs.stage}}"
          echo "runner: ${{inputs.runner}}"
          echo "notifications: ${{inputs.notifications}}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: install-aws-cli
        if: contains( inputs.runner, 'k8s-runners-stg' )
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64

      - name: Get Commit Hash
        id: get-commit-ids
        run: |
          echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_OUTPUT

          short_commit_hash=$(echo ${{ github.sha }} | cut -c 1-7)
          echo "SHORT_COMMIT_HASH=$short_commit_hash" >> $GITHUB_ENV
          echo "SHORT_COMMIT_HASH=$short_commit_hash" >> $GITHUB_OUTPUT

          echo "Commit Hash: ${{env.COMMIT_HASH}}"
          echo "Short Commit Hash: ${{env.SHORT_COMMIT_HASH}}"

      - name: Get version tag
        continue-on-error: true
        id: version-tag
        run: |
          echo "RELEASE_TAG=null" >> $GITHUB_ENV
          echo "RELEASE_TAG=null" >> $GITHUB_OUTPUT
          tag=$(git describe --exact-match --tags HEAD)
          if [[ -n "$tag" ]]; then
              echo "Current commit has a tag: $tag"
              echo "RELEASE_TAG=$tag"
              echo "RELEASE_TAG=$tag" >> $GITHUB_ENV
              echo "RELEASE_TAG=$tag" >> $GITHUB_OUTPUT
          else
              echo "Current commit does not have a tag"
          fi

      - name: Get stage
        id: stage
        env:
          STAGE_INPUT: ${{ inputs.stage }}
        run: |
          if [[ "$STAGE_INPUT" =~ ^staging([1-9]|10)?$ ]]; then
            STAGE=${STAGE_INPUT/staging/}
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
            echo "STAGE=$STAGE_INPUT" >> $GITHUB_ENV
            echo "STAGE=$STAGE_INPUT" >> $GITHUB_OUTPUT
            echo "STAGE_SHORT=st$STAGE" >> $GITHUB_ENV
            echo "STAGE_SHORT=st$STAGE" >> $GITHUB_OUTPUT
            echo "Se está ejecutando como staging"
          else
            echo "Se está ejecutando como prod"
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
            echo "STAGE=$STAGE_INPUT" >> $GITHUB_ENV
            echo "STAGE=$STAGE_INPUT" >> $GITHUB_OUTPUT
            echo "STAGE_SHORT=$STAGE_INPUT" >> $GITHUB_ENV
            echo "STAGE_SHORT=$STAGE_INPUT" >> $GITHUB_OUTPUT
          fi

      - name: Extract branch name - Trunk Mode
        id: extract_branch_trunk
        if: contains( inputs.branching_mode, 'trunk' )
        shell: bash
        run: |
          echo "BRANCH_NAME=$GITHUB_REF_NAME" 
          echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV 
          echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT 

      - name: Extract branch name - Gitflow Mode
        id: extract_branch
        if: contains(fromJson('["push", "release", "pull_request"]'), github.event_name)
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            BRANCH_NAME=${{github.base_ref}}
            echo "Branch name extracted from pull request: $BRANCH_NAME"
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == 'release' && "${{ github.event.release.prerelease }}" == true ]]; then
            echo "This is a pre-release."
            BRANCH_NAME="beta"
            echo "BRANCH_NAME=beta" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == 'release' ]]; then
            echo "This is a full release."
            BRANCH_NAME="master"
            echo "BRANCH_NAME=master" >> $GITHUB_ENV
          fi
          echo "Extracted branch name: $BRANCH_NAME"

      - name: Set release/branch version - staging
        id: set-release-staging
        if: contains(fromJson('["workflow_dispatch"]'), inputs.trigger_type)
        run: |
          RELEASE_VERSION=${{ inputs.staging_target }}
          RELEASE_VERSION=$(echo $RELEASE_VERSION | sed s/staging/v/g)
          RELEASE_VERSION=$RELEASE_VERSION".0.0-staging-"${{ env.SHORT_COMMIT_HASH}}
          echo "Final staging release version: "$RELEASE_VERSION
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get AWS Codebuild project
        id: set-project-name
        shell: bash
        run: |
          SERVICE_NAME=$(cat .infra/infra-config.json | jq .name | tr -d '"')
          echo "SERVICE_NAME=$SERVICE_NAME"
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "PROJECT=$(echo $SERVICE_NAME-${{ env.STAGE }})"
          echo "PROJECT=$(echo $SERVICE_NAME-${{ env.STAGE }})" >> $GITHUB_ENV
          echo "PROJECT=$(echo $SERVICE_NAME-${{ env.STAGE }})" >> $GITHUB_OUTPUT

  codebuild-check:
    runs-on: ${{ inputs.runner }}
    name: Codebuild Project Checks
    needs: sets-variables
    outputs:
      new_stage: ${{ steps.check-project.outputs.new_stage }}
      project_exist: ${{ steps.check-project.outputs.project_exist }}
      codebuild_project: ${{ env.CODEBUILD_PROJECT }}
      
    steps:

      - id: install-aws-cli
        if: contains( inputs.runner, 'k8s-runners-stg' )
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64

      - name: Configure AWS Credentials - CICD
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CICD_AWS_REGION }}

      - name: Check if project exists
        id: check-project
        shell: bash
        run: |
          CODEBUILD=$(aws codebuild list-projects --region ${{ secrets.CICD_AWS_REGION }} --query 'projects[?ends_with(@,`${{ needs.sets-variables.outputs.PROJECT }}`) == `true`]' | jq ".[0]" | tr -d '"')
          echo "Codebuild project: "$CODEBUILD
          if [[ $CODEBUILD != "null" ]]; \
          then \
            echo "new_stage=false"; \
            echo "new_stage=false" >> $GITHUB_OUTPUT; \
            echo "project_exist=true"; \
            echo "project_exist=true" >> $GITHUB_OUTPUT; \
          elif [[ $CODEBUILD == "null" ]]; \
          then \
            echo "project_exist=false"; \
            echo "project_exist=false" >> $GITHUB_OUTPUT; \
            echo "new_stage=true"; \
            echo "new_stage=true" >> $GITHUB_OUTPUT; \
          fi
          echo "CODEBUILD_PROJECT=$CODEBUILD"
          echo "CODEBUILD_PROJECT=$CODEBUILD" >> $GITHUB_OUTPUT
          echo "CODEBUILD_PROJECT=$CODEBUILD" >> $GITHUB_ENV

  aws-build:
    runs-on: ${{ inputs.runner }}
    name: AWS CodeBuild Trigger and Helm Push
    needs: [sets-variables, codebuild-check]
    outputs:
      release_version: ${{ env.RELEASE_VERSION }}
    steps:

      - id: install-aws-cli
        if: contains( inputs.runner, 'k8s-runners-stg' )
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64

      - name: Set release version - Staging
        id: set-release-staging
        if: startsWith(inputs.stage, 'staging')
        run: |
          RELEASE_VERSION=${{ inputs.stage }}
          RELEASE_VERSION=$(echo $RELEASE_VERSION | sed s/staging/v/g)
          RELEASE_VERSION=$RELEASE_VERSION".0.0-staging-"${{ needs.sets-variables.outputs.SHORT_COMMIT_HASH}}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "Final staging release version: "$RELEASE_VERSION

      - name: Set release version - Production
        id: set-release-prod
        if: contains(fromJson('["production", "beta"]'), inputs.stage)
        run: |
          echo "RELEASE_VERSION=${{ needs.sets-variables.outputs.RELEASE_TAG }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ needs.sets-variables.outputs.RELEASE_TAG }}" >> $GITHUB_OUTPUT
          echo "Final production release version: $RELEASE_VERSION }}"

      - name: Configure AWS Credentials - Shared
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.SHARED_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SHARED_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SHARED_AWS_REGION }}

      - name: Check ECR image tag
        id: check-ecr-tag
        continue-on-error: true
        run: |
          ECR_REPOSITORY=$(aws ecr describe-repositories --region ${{ secrets.SHARED_AWS_REGION }} --query 'repositories[?ends_with(repositoryName, `${{ needs.sets-variables.outputs.SERVICE_NAME}}`) == `true`]' | jq ".[0].repositoryName" | tr -d '"')
          echo "ECR Repository: "$ECR_REPOSITORY

          if [[ ${{startsWith(inputs.stage, 'staging')}} ]]; then
            aws ecr describe-images --repository-name $ECR_REPOSITORY --region ${{ secrets.SHARED_AWS_REGION }} --image-ids imageTag=${{ env.RELEASE_VERSION}}
          else
            aws ecr describe-images --repository-name $ECR_REPOSITORY --region ${{ secrets.SHARED_AWS_REGION }} --image-ids imageTag=${{ needs.sets-variables.outputs.RELEASE_TAG}}
          fi

      - name: Check ECR image tag outcome
        id: check-ecr
        run: |
          echo "ECR check outcome: "${{steps.check-ecr-tag.outcome}}
          if [ '${{steps.check-ecr-tag.outcome}}' == 'failure' ]; then
            echo "Release version is not builded"
            ECR_IMAGE_EXIST=false
          elif [ '${{steps.check-ecr-tag.outcome}}' == 'success' ]; then
            echo "Release version is already builded"
            ECR_IMAGE_EXIST=true
          fi
          echo "ECR_IMAGE_EXIST=$ECR_IMAGE_EXIST" >> $GITHUB_ENV;
          echo "ECR_IMAGE_EXIST=$ECR_IMAGE_EXIST" >> $GITHUB_OUTPUT;
          echo "ECR_IMAGE_EXIST=$ECR_IMAGE_EXIST"

      - name: Configure AWS Credentials - CICD
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CICD_AWS_REGION }}

      - name: Select Codebuild Source
        id: select-source
        shell: bash
        run: |
          if [[ ${{needs.sets-variables.outputs.RELEASE_TAG}} != "null" ]]; then \
            CODEBUILD_SOURCE=${{needs.sets-variables.outputs.RELEASE_TAG}}
          else
            CODEBUILD_SOURCE=$GITHUB_REF_NAME
          fi
          echo "CODEBUILD_SOURCE=$CODEBUILD_SOURCE"
          echo "CODEBUILD_SOURCE=$CODEBUILD_SOURCE" >> $GITHUB_ENV 
          echo "CODEBUILD_SOURCE=$CODEBUILD_SOURCE" >> $GITHUB_OUTPUT

      - name: Get Codebuild Project Name
        id: get-project-name
        if: needs.codebuild-check.outputs.project_exist
        shell: bash
        run: |
          CODEBUILD=$(aws codebuild list-projects --region ${{ secrets.CICD_AWS_REGION }} --query 'projects[?ends_with(@,`${{ needs.sets-variables.outputs.PROJECT }}`) == `true`]' | jq ".[0]" | tr -d '"')
          echo "CODEBUILD_PROJECT_FINAL=$CODEBUILD" 
          echo "CODEBUILD_PROJECT_FINAL=$CODEBUILD" >> $GITHUB_ENV
          echo contains(fromJson('["true"]'), steps.check-project.outputs.project_exist) && contains(fromJson('["push", "release", "workflow_dispatch"]'), github.event_name) && contains(fromJson('["failure"]'), steps.check-ecr-tag.outcome)
          echo contains(fromJson('["true"]'), steps.check-project.outputs.project_exist)
          echo contains(fromJson('["push", "release", "workflow_dispatch"]'), github.event_name)
          echo contains(fromJson('["failure"]'), steps.check-ecr-tag.outcome)

      - name: Run AWS CodeBuild
        id: codebuild
        if: true #contains(fromJson('["true"]'), steps.check-project.outputs.project_exist) && contains(fromJson('["push", "release", "workflow_dispatch"]'), github.event_name) && contains(fromJson('["failure"]'), steps.check-ecr-tag.outcome)
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          CODEBUILD__sourceVersion: ${{ env.CODEBUILD_SOURCE }}
          CODEBUILD__logsConfigOverride__cloudWatchLogs__status: 'ENABLED'
        with:
          projectName: ${{ env.CODEBUILD_PROJECT_FINAL }}
          buildspec: '{
              "environmentVariablesOverride":[
                { "name":"RELEASE_VERSION", "value":"${{ env.RELEASE_VERSION }}", "type": "PLAINTEXT" },
                { "name":"INFRA_TEMPLATE_VERSION", "value":"${{ inputs.infra_templates_version }}", "type": "PLAINTEXT" }
              ]
            }'

      - name: Google Chat Notification - Without codebuild
        if: contains(fromJson('["true"]'), steps.check-project.outputs.project_exist ) && contains(fromJson('["push", "release", "workflow_dispatch"]'), github.event_name) && contains(fromJson('["success"]'), steps.check-ecr-tag.outcome)
        uses: nakamuraos/google-chat-notifications@v2.1.0
        with:
          title: Image Build
          subtitle: ${{ env.RELEASE_VERSION }}
          webhookUrl: ${{ secrets.GOOGLE_WEBHOOK }}
          status: 'success'

      - name: Output checks
        shell: bash
        run: |
          echo "new_stage: " ${{ steps.check-project.outputs.new_stage }}
          echo "stage_check: " ${{ steps.check-project.outputs.project_exist }}
          echo "stage: " ${{ steps.set_project_name.outputs.stage }}
          echo "env_check: " ${{ steps.set_project_name.outcome }}
          echo "release_version: " ${{ env.RELEASE_VERSION}}
