name: Preflight Checks

on: 
  workflow_call:

jobs:
  check_user_group:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar grupo de usuario
        id: check_group
        run: |
          username="${{ github.actor }}"
          group="@ProjectCORTeam/prod-deployers"

          # Obtener información del usuario
          user_url="https://api.github.com/users/$username"
          user_response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$user_url")
          user_groups_url=$(echo "$user_response" | jq -r '.organizations_url')

          # Obtener los grupos del usuario
          groups_response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$user_groups_url")
          groups=$(echo "$groups_response" | jq -r '.[].login')

          # Verificar si el usuario pertenece al grupo especificado
          if echo "$groups" | grep -q "$group"; then
            echo "El usuario $username pertenece al grupo $group"
          else
            echo "El usuario $username no pertenece al grupo $group"
            exit 1
          fi
