name: Preflight Checks

on: 
  workflow_call:
    inputs: 
      stage:
        required: true
        type: string
      organization:
        required: true
        type: string
      team:
        required: true
        type: string

jobs:
  check_user_group:
    runs-on: ubuntu-latest

    steps:
      - name: Verify user membership
        id: check_group_membership
        run: |
          # Obtener información del usuario
          membership_url="https://api.github.com/orgs/ProjectCORTeam/teams/prod-deployers/memberships/cferrer101"
          membership_url="https://api.github.com/orgs/${{inputs.organization}}/teams/${{inputs.team}}/memberships/${{github.actor}}"
          membership_response=$(curl -s -H "Authorization: Bearer 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" "$membership_url")
          membership_response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$membership_url")
          echo $membership_response | jq 

          state=$(echo "$response" | jq -r '.state')
          
          if [[ "$state" == "active" ]]; then
            echo "User have permission to execute this workflow for ${{ inputs.stage }} stage"
          else
            echo "You don't have permission to execute this workflow for ${{ inputs.stage }} stage"
            exit 1
