name: Release notification
on:
  workflow_call:

jobs:
  notify_google_chat:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "cards": [{
              "header": {
                "title": "${{ github.repository }}: Deploy finished",
                "subtitle": "Release ${{ github.ref_name }}",
                "imageUrl": "https://digital-assets.projectcor.com/integrations/COR_icon.png"          
              },
              "sections": [{
                "widgets": [{
                  "keyValue": {
                      "topLabel": "New Release",
                      "content": "- Project: ${{ github.repository }}.\n- Committer: GITHUB.\n- Release: ${{ github.head_ref }}",
                      "contentMultiline": "true",
                      "bottomLabel": "",
                      "onClick": {
                            "openLink": {
                              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                            }
                        },
                      "icon": "DESCRIPTION"
                    }
                }]
              }]
            }]
          }'
