name: Web Custom Build

on: 
  workflow_call:
    inputs: 
      trigger_type:
        required: true
        type: string
      artifact_s3_uri:
        required: true
        type: string
      artifact_s3_key:
        required: true
        type: string
      notifications:
        required: false
        type: boolean
        default: true
        description: "Enable notifications to cloud or team owner flag"
      
    secrets: 
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      STG_AWS_ACCESS_KEY_ID:
        required: true
      STG_AWS_SECRET_ACCESS_KEY:
        required: true
      STG_AWS_REGION:
        required: true
      PROD_AWS_ACCESS_KEY_ID:
        required: true
      PROD_AWS_SECRET_ACCESS_KEY:
        required: true
      PROD_AWS_REGION:
        required: true
      SHARED_AWS_ACCESS_KEY_ID:
        required: true
      SHARED_AWS_SECRET_ACCESS_KEY:
        required: true
      SHARED_AWS_REGION:
        required: true
      GOOGLE_WEBHOOK:
        required: true

jobs:

  aws_codedeploy_deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }}
    name: AWS CodeDeploy Deploy
    steps:
      - name: Configure AWS Credentials
        if: ${{ contains(fromJSON('["production", "beta"]'), vars.CODEDEPLOY_DEPLOYMENT_GROUP) }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS Credentials
        if: ${{ contains(fromJSON('["stg"]'), vars.CODEDEPLOY_DEPLOYMENT_GROUP) }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STG_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.STG_AWS_REGION }}

      # Step 4: Tell AWS CodeDeploy to start the deployment
      - name: Trigger AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ vars.CODEDEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ vars.CODEDEPLOY_S3_ARTIFACTS }},bundleType=tar.gz,key=${{ inputs.artifact_s3_key }} \
            --description "Deployment triggered by GitHub Actions commit ${{ github.sha }}"
